= Showcase for Hadoop with CDC on Quarkus

This project holds a showcase for Hadoop with CDC on Quarkus.

== Problems

Apparently I cannot start the datanode in Hadoop >=3.0.0:

- *2.8.1* Starts fine
- *2.9.2* Starts fine
- *3.0.0* Exception <a 'java/lang/ClassNotFoundException': org/apache/commons/configuration2/BaseConfigurationBeanInfo> (0x000000076dd6d438) thrown at [/home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-alpine-linux-x64-temurin/workspace/build/src/hotspot/
- *3.1.0* Exception <a 'java/lang/ClassNotFoundException': org/apache/commons/configuration2/BaseConfigurationBeanInfo> (0x000000076dd02590) thrown at [/home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-alpine-linux-x64-temurin/workspace/build/src/hotspot/
- *3.2.0* Exception <a 'java/lang/ClassNotFoundException': org/apache/log4j/WriterAppenderCustomizer> (0x000000076de89748) thrown at [/home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-alpine-linux-x64-temurin/workspace/build/src/hotspot/src/share/vm/class
- *3.3.0* Exception <a 'java/lang/ClassNotFoundException': org/apache/log4j/RollingFileAppenderCustomizer> (0x000000076e2246b8) thrown at [/home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-alpine-linux-x64-temurin/workspace/build/src/hotspot/src/share/vm/
- *3.3.4* Exception <a 'java/lang/ClassNotFoundException': org/apache/log4j/WriterAppenderCustomizer> (0x000000076e45ab38) thrown at [/home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-alpine-linux-x64-temurin/workspace/build/src/hotspot/src/share/vm/class


== Links

=== Hadoop

- https://medium.com/analytics-vidhya/hadoop-single-node-cluster-on-docker-e88c3d09a256
- https://github.com/rancavil/hadoop-single-node-cluster
- https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html
- https://www.edureka.co/blog/install-hadoop-single-node-hadoop-cluster
- https://stackoverflow.com/questions/41266403/how-to-access-hadoop-web-ui-in-linux
- https://www.digitalocean.com/community/tutorials/how-to-install-hadoop-in-stand-alone-mode-on-ubuntu-20-04

=== Debezium

- https://hub.docker.com/r/debezium/server
- https://debezium.io/documentation/reference/stable/operations/debezium-server.html
- https://github.com/memiiso/debezium-server-iceberg
- https://debezium.io/blog/2021/10/20/using-debezium-create-data-lake-with-apache-iceberg/
- https://iceberg.apache.org/
- https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#FsURIvsHTTP_URL
- https://stackoverflow.com/questions/59978213/debezium-could-not-access-file-decoderbufs-using-postgres-11-with-default-plug